kbm_text_map = {
'ConceptMouseRecenter':'Mouse Recenter',
'ConceptContextualInteraction':'Contextual Interaction',
'ConceptPitch_P':'Pitch Up',
'ConceptPitch_N':'Pitch Down',
'ConceptYaw_P':'Yaw Right',
'ConceptYaw_N':'Yaw Left',
'ConceptRoll_P':'Roll Right',
'ConceptRoll_N':'Roll Left',
'ConceptThrottle_P':'Throttle Increase',
'ConceptThrottle_N':'Throttle Decrease',
'ConceptAfterburner':'Boost',
'ConceptDrift':'Drift (While Boosting)',
'ConceptFire':'Fire',
'ConceptFireAuxiliaryWeaponOneMain':'Fire Left Auxiliary',
'ConceptFireAuxiliaryWeaponOneDoubleTap':'Dumb-Fire Left Auxiliary',
'ConceptFireAuxiliaryWeaponTwoMain':'Fire Right Auxiliary',
'ConceptFireAuxiliaryWeaponTwoDoubleTap':'Dumb-Fire Right Auxiliary',
'ConceptFireCountermeasure':'Deploy Countermeasures',
'ConceptScoreboard':'Show Loadout',
'ConceptIncreaseEnginePower':'Increase Engine Power',
'ConceptMaximizeEnginePower':'Maximize Engine Power',
'ConceptIncreaseWeaponPower':'Increase Weapon Power',
'ConceptMaximizeWeaponPower':'Maximize Weapon Power',
'ConceptIncreaseShieldPower':'Increase Shield Power',
'ConceptMaximizeShieldPower':'Maximize Shield Power',
'ConceptResetSystemsPower':'Balance Power',
'ConceptShieldFront':'Focus Shields (Front)',
'ConceptShieldBack':'Focus Shields (Rear)',
'ConceptShieldBalance':'Focus Shields (Balanced)',
'ConceptEmergencyPowerTransferEngine':'Convert Power (Engines)',
'ConceptEmergencyPowerTransferWeapon':'Convert Power (Weapons)',
'ConceptEmergencyPowerTransferBalance':'Convert Power (Balanced)',
'ConceptPowerTransfer':'Focus Shields / Convert Power',
'ConceptPowerTransferMenuSelect':'Shield / Power Menu Select',
'ConceptPowerTransferMenuX_P':'Shield / Power Menu Right',
'ConceptPowerTransferMenuX_N':'Shield / Power Menu Left',
'ConceptPowerTransferMenuY_P':'Shield / Power Menu Up',
'ConceptPowerTransferMenuY_N':'Shield / Power Menu Down',
'ConceptTargetSelect':'Select Target Ahead',
'ConceptTargetCycleNext':'Cycle Targets',
'ConceptTargetHighestThreat':'Target My Attacker',
'ConceptTargetingMenu':'Targeting Wheel',
'ConceptTargetingMenuSelectTargetingMethod':'Targeting Wheel (Toggle Mode) - Select',
'ConceptTargetingMenuX_P':'Targeting Wheel X- Right',
'ConceptTargetingMenuX_N':'Targeting Wheel X - Left',
'ConceptTargetingMenuY_P':'Targeting Wheel Y - Up',
'ConceptTargetingMenuY_N':'Targeting Wheel Y - Down',
'ConceptTargetingMenuCycleAllEnemies':'Targeting Wheel Shortcut - All Enemies',
'ConceptTargetingMenuCycleEnemySquadron':'Targeting Wheel Shortcut - Enemy Squadron',
'ConceptTargetingMenuCycleEnemyAI':'Targeting Wheel Shortcut - Enemy AI',
'ConceptTargetingMenuCycleFlagshipSystems':'Targeting Wheel Shortcut - Flagship Systems',
'ConceptTargetingMenuCycleAllAllies':'Targeting Wheel Shortcut - All Allies',
'ConceptTargetingMenuCycleMySquadron':'Targeting Wheel Shortcut - My Squadron',
'ConceptTargetingMenuCycleTargetAttackers':'Targeting Wheel Shortcut - Target\'s Attackers',
'ConceptTargetingMenuCycleLastAttackers':'Targeting Wheel Shortcut - Last Attackers',
'ConceptTargetingMenuCycleObjectives':'Targeting Wheel Shortcut - Objectives',
'ConceptTargetingMenuCycleMissiles':'Targeting Wheel Shortcut - Missiles',
'ConceptTargetPing':'Ping Target',
'ConceptPingSelf':'Acknowledge Ping',
'ConceptCommMenu':'Comms Wheel',
'ConceptCommMenuSelect':'Comms Wheel (Toggle Mode) - Select',
'ConceptCommMenuX_P':'Comms Wheel - Navigate Right',
'ConceptCommMenuX_N':'Comms Wheel - Navigate Left',
'ConceptCommMenuY_P':'Comms Wheel - Navigate Up',
'ConceptCommMenuY_N':'Comms Wheel - Navigate Down',
'ConceptFreeLookTrigger':'Recalibrate VR',
'ConceptFreeLook':'Free Look',
'ConceptFreeLookCameraUp':'Free Look - Camera Pitch Up',
'ConceptFreeLookCameraDown':'Free Look - Camera Pitch Down',
'ConceptFreeLookCameraLeft':'Free Look - Camera Yaw Left',
'ConceptFreeLookCameraRight':'Free Look - Camera Yaw Right',
'ConceptCameraPitch_P':'Quick Look - Camera Pitch Up',
'ConceptCameraPitch_N':'Quick Look - Camera Pitch Down',
'ConceptCameraYaw_P':'Quick Look - Camera Yaw Left',
'ConceptCameraYaw_N':'Quick Look - Camera Yaw Right',
'ConceptCommMenuHelpMe':'Comms Wheel Shortcut - Help Me',
'ConceptCommMenuCheer':'Comms Wheel Shortcut - Cheer',
'ConceptCommMenuBrag':'Comms Wheel Shortcut - Brag',
'ConceptCommMenuBoo':'Comms Wheel Shortcut - Boo',
'ConceptCommMenuRegroup':'Comms Wheel Shortcut - Regroup',
'ConceptCommMenuBattleCry':'Comms Wheel Shortcut - Battle Cry',
'ConceptCommMenuThank':'Comms Wheel Shortcut - Thank',
'ConceptCommMenuPraise':'Comms Wheel Shortcut - Praise'
}

joystick_text_map = {
'ConceptMouseRecenter':'Mouse Recenter',
'ConceptContextualInteraction':'Contextual Interaction',
'ConceptPitch_P':'Pitch Up',
'ConceptPitch_N':'Pitch Down',
'ConceptYaw_P':'Yaw Right',
'ConceptYaw_N':'Yaw Left',
'ConceptRoll_P':'Roll Right',
'ConceptRoll_N':'Roll Left',
'ConceptThrottle_P':'Throttle Increase',
'ConceptThrottle_N':'Throttle Decrease',
'ConceptAfterburner':'Combo - Boost / Drift',
'ConceptDrift':'Drift',
'ConceptFire':'Fire',
'ConceptFireAuxiliaryWeaponOneMain':'Combo - Left Aux / Dumb-Fire',
'ConceptFireAuxiliaryWeaponOneDoubleTap':'Dumb-Fire Left Auxiliary',
'ConceptFireAuxiliaryWeaponTwoMain':'Combo - Right Aux / Dumb-Fire',
'ConceptFireAuxiliaryWeaponTwoDoubleTap':'Dumb-Fire Right Auxiliary',
'ConceptFireCountermeasure':'Deploy Countermeasures',
'ConceptScoreboard':'Show Loadout',
'ConceptControlEnginePower':'Combo - Power to Engines / Max',
'ConceptIncreaseEnginePower':'Increase Engine Power',
'ConceptMaximizeEnginePower':'Maximize Engine Power',
'ConceptControlWeaponPower':'Combo - Power to Weapons / Max',
'ConceptIncreaseWeaponPower':'Increase Weapon Power',
'ConceptMaximizeWeaponPower':'Maximize Weapon Power',
'ConceptControlShieldPower':'Combo - Power to Shields / Max',
'ConceptIncreaseShieldPower':'Increase Shield Power',
'ConceptMaximizeShieldPower':'Maximize Shield Power',
'ConceptControlBalancePower':'Balance Power',
'ConceptShieldFront':'Focus Shields (Front)',
'ConceptShieldBack':'Focus Shields (Rear)',
'ConceptShieldBalance':'Focus Shields (Balanced)',
'ConceptEmergencyPowerTransferEngine':'Convert Power (Engines)',
'ConceptEmergencyPowerTransferWeapon':'Convert Power (Weapons)',
'ConceptEmergencyPowerTransferBalance':'Convert Power (Balanced)',
'ConceptPowerTransfer':'Focus Shields / Convert Power',
'ConceptPowerTransferMenuSelect':'Shield / Power Menu Select',
'ConceptPowerTransferMenuX_P':'Shield / Power Menu Right',
'ConceptPowerTransferMenuX_N':'Shield / Power Menu Left',
'ConceptPowerTransferMenuY_P':'Shield / Power Menu Up',
'ConceptPowerTransferMenuY_N':'Shield / Power Menu Down',
'ConceptTargeting':'Combo - Select Target Ahead / Targeting Wheel',
'ConceptTargetSelect':'Select Target Ahead',
'ConceptTargetCycle':'Combo - Cycle Targets / Target My Attacker',
'ConceptTargetCycleNext':'Cycle Targets',
'ConceptTargetHighestThreat':'Target My Attacker',
'ConceptTargetingMenu':'Targeting Wheel',
'ConceptTargetingMenuSelectTargetingMethod':'Targeting Wheel (Toggle Mode) - Select',
'ConceptTargetingMenuX_P':'Targeting Wheel X - Right',
'ConceptTargetingMenuX_N':'Targeting Wheel X - Left',
'ConceptTargetingMenuY_P':'Targeting Wheel Y - Up',
'ConceptTargetingMenuY_N':'Targeting Wheel Y - Down',
'ConceptTargetingMenuCycleAllEnemies':'Targeting Wheel Shortcut - All Enemies',
'ConceptTargetingMenuCycleEnemySquadron':'Targeting Wheel Shortcut - Enemy Squadron',
'ConceptTargetingMenuCycleEnemyAI':'Targeting Wheel Shortcut - Enemy AI',
'ConceptTargetingMenuCycleFlagshipSystems':'Targeting Wheel Shortcut - Flagship Systems',
'ConceptTargetingMenuCycleAllAllies':'Targeting Wheel Shortcut - All Allies',
'ConceptTargetingMenuCycleMySquadron':'Targeting Wheel Shortcut - My Squadron',
'ConceptTargetingMenuCycleTargetAttackers':'Targeting Wheel Shortcut - Target\'s Attackers',
'ConceptTargetingMenuCycleLastAttackers':'Targeting Wheel Shortcut - Last Attackers',
'ConceptTargetingMenuCycleObjectives':'Targeting Wheel Shortcut - Objectives',
'ConceptTargetingMenuCycleMissiles':'Targeting Wheel Shortcut - Missiles',
'ConceptCommunication':'Combo - Ping / Ack / Comms Wheel',
'ConceptTargetPing':'Ping Target',
'ConceptPingSelf':'Acknowledge Ping',
'ConceptCommMenu':'Comms Wheel',
'ConceptCommMenuSelect':'Comms Wheel (Toggle Mode) - Select',
'ConceptCommMenuX_P':'Comms Wheel - Navigate Right',
'ConceptCommMenuX_N':'Comms Wheel - Navigate Left',
'ConceptCommMenuY_P':'Comms Wheel - Navigate Up',
'ConceptCommMenuY_N':'Comms Wheel - Navigate Down',
'ConceptFreeLookTrigger':'Recalibrate VR',
'ConceptFreeLook':'Free Look',
'ConceptFreeLookCameraUp':'Free Look - Camera Pitch Up',
'ConceptFreeLookCameraDown':'Free Look - Camera Pitch Down',
'ConceptFreeLookCameraLeft':'Free Look - Camera Yaw Left',
'ConceptFreeLookCameraRight':'Free Look - Camera Yaw Right',
'ConceptCameraPitch_P':'Quick Look - Camera Pitch Up',
'ConceptCameraPitch_N':'Quick Look - Camera Pitch Down',
'ConceptCameraYaw_P':'Quick Look - Camera Yaw Left',
'ConceptCameraYaw_N':'Quick Look - Camera Yaw Right',
'ConceptCommMenuHelpMe':'Comms Wheel Shortcut - Help Me',
'ConceptCommMenuCheer':'Comms Wheel Shortcut - Cheer',
'ConceptCommMenuBrag':'Comms Wheel Shortcut - Brag',
'ConceptCommMenuBoo':'Comms Wheel Shortcut - Boo',
'ConceptCommMenuRegroup':'Comms Wheel Shortcut - Regroup',
'ConceptCommMenuBattleCry':'Comms Wheel Shortcut - Battle Cry',
'ConceptCommMenuThank':'Comms Wheel Shortcut - Thank',
'ConceptCommMenuPraise':'Comms Wheel Shortcut - Praise'
}